# kubeseal --cert kubeseal.pem --format yaml < secret-argocd-repo > sealedsecret-argocd-repo.yaml 
apiVersion: v1
kind: Secret
metadata:
  name: argocd-rep
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  url: https://github.com/your-username/your-repo.git
  username: your-username
  password: your-pat
