apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ./configmap-cmp-cluster-env.yaml
  - ./configmap-cmp-kustomized-helm.yaml
  - argocd-argocd.yaml
# patchesStrategicMerge:
#- version.yml

