apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress
  project: default
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: "4.7.1"
    # helm:
      # Helm values files for overriding values in the helm chart
      # The path is relative to the spec.source.path directory defined above
      # valueFiles:
      # ../values-kube-prometheus.yaml' resolved to outside repository root
      #  - ../values-kube-prometheus.yaml
      #  - ../values-override.yaml
    #  values: |
    #    rbac:
    #      create: true
  syncPolicy:
    # syncOptions: {}
    automated:
      prune: true
      selfHeal: true
