apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ksops
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: ksops
    server: {{ .Values.spec.destination.server }}
  project: default
  # https://argo-cd.readthedocs.io/en/stable/proposals/server-side-apply/
  syncPolicy:
    syncOptions: # https://www.arthurkoziel.com/fixing-argocd-crd-too-long-error/
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
  source:
    path: "{{ .Values.spec.source.rootPath }}/ksops"
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
