apiVersion: operator.open-cluster-management.io/v1
kind: Klusterlet
metadata:
  name: klusterlet
  annotations:
    # argocd.argoproj.io/hook: Sync
    # argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  clusterName: spoke
  deployOption:
    mode: Singleton
  externalServerURLs:
    - url: 'https://argocd-conductr-control-plane:6443'
  imagePullSpec: 'quay.io/open-cluster-management/registration-operator:v0.15.1'
  namespace: open-cluster-management-agent
  registrationImagePullSpec: 'quay.io/open-cluster-management/registration:v0.15.1'
  workImagePullSpec: 'quay.io/open-cluster-management/work:v0.15.1'
