# https://access.redhat.com/solutions/6158462
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: basic-argocd-application-controller
  namespace: default
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - "*"
  #- get
  #- list
  #- watch
  #- Get
  #- List
  #- Watch
  #- Patch
---
#apiVersion: rbac.authorization.k8s.io/v1beta1
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: basic-argocd-application-controller
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io  
  kind: Role
  name: basic-argocd-application-controller
subjects:
- kind: ServiceAccount
  name: basic-argocd-application-controller 
  namespace: argocd  