apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster
  namespace: argocd
spec:
  generators:
  - list: # We may want to try another generator
      elements:
      - cluster: local
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-cluster'
    spec:
      project: default
      source:
        repoURL: https://github.com/deas/argocd-conductr
        targetRevision: main # HEAD
        path: apps/root # For moment, could use cluster/{{cluster}}
      # Sync policy
      syncPolicy:
        automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
          prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
          selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
          allowEmpty: false # Allows deleting all application resources during automatic syncing ( false by default ).
        #syncOptions:     # Sync options which modifies sync behavior
        #- Validate=false # disables resource validation (equivalent to 'kubectl apply --validate=false') ( true by default ).
        #- CreateNamespace=true # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.
        #- PrunePropagationPolicy=foreground # Supported policies are background, foreground and orphan.
        #- PruneLast=true # Allow the ability for resource pruning to happen as a final, implicit wave of a sync operation
        #- ServerSideApply=true
        #managedNamespaceMetadata: # Sets the metadata for the application namespace. Only valid if CreateNamespace=true (see above), otherwise it's a no-op.
        #  labels: # The labels to set on the application namespace
        #    any: label
        #    you: like
        #  annotations: # The annotations to set on the application namespace
        #   the: same
        #    applies: for
        #    annotations: on-the-namespace
        retry:
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m0s
          limit: 2
        #syncOptions:
        #- ServerSideApply=true
      destination:
        server: '{{url}}'
        namespace: argocd # default
