apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: argocd-operator
  namespace: openshift-operators
spec:
  channel: alpha
  name: argocd-operator
  source: operatorhubio-catalog
  sourceNamespace: operator-lifecycle-manager # olm
  config:
    env:
      - name: ARGOCD_CLUSTER_CONFIG_NAMESPACES
        value: argocd
    #- name: CONTROLLER_CLUSTER_ROLE
    #  value: custom-controller-role
    #- name: SERVER_CLUSTER_ROLE
    #  value: custom-server-role
