apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: klusterlet
  namespace: openshift-operators
spec:
  channel: stable
  name: klusterlet
  source: operatorhubio-catalog
  sourceNamespace: openshift-operator-lifecycle-manager # olm
