{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "argocd-notifications-secret",
    "namespace": "argocd",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "argocd-notifications-secret",
        "namespace": "argocd",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "slack-token": "AgDFAu8CKIcXE6DMQyn8LckCs1MhrM4wgTdvLyQjFb+9yUgEAu+ZpHlAX/mCJVaA62wF7b5zkkrIsEVFcOXBzsukyiXl7xXBKbodsFgvf3EJwOambXUzH7JSBiZZOfnthrq3Gd3LTdm1qGYj17lNFRM6xeF4AAgnDjbBwawkW72c4vb2531+mUONzX4by3GzINWD0v8wgt9HghODsTOBKS0QOBRyP04aPiqC+pG5dvfxnu0FjLEqPTglMtnp5aufr8bx042pvNH/hOlOFNy97A9bX2Gw14vi11Ebct6puKxkRMJHRlvV1mAf6GzArVAcLMrO7pH0oKF5wh/mwQNdr+rpOk08Sar0HdlbCKkXKP8iwMDxBxWeSOHb2nN5Az7Klnj7vDZ50tAlMvJSUagKT8BwsOkIzKR/A53y6wg/xNABBAEoelsuaCKTi0XI07PtAtXHUK0OYoV8kuSY2/0Oz5gjFneoWBxoPfIhdU0vwtXWGDcVX4Zk1d5HbTVDe2RVJTBfoMFYVwSN7rTqplKLb+RxaMZSTnmtp5mGqfAPln+wjATKk2Gm6vsR46tLkScW7jI8f6Moefb/f6hloiQKhMXfCQCsar8z7Da/MJWmUo1Wx75x6OjRyFc+woRH/CqTDz1oQMGIrWiYoezjyXM8DRIG0BOhX2fUsB66QJKh5e/9ItdwZzQF830sSPSeS23o+01VY10IUpLGCt4PxCeGXaezqbMmMsaGz9URMJrWNUoZRsI+RjBWkULUQNupOCgsld23V7VJP9E="
    }
  }
}
