apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
spec:
  encryptedData:
    slack-token: AgCG53qLqRz7xp/izN1Ss+d2YDy9jRiPABuw1YRBcqpW0QT3icQWPo89lEHbiu2GYfmAa0Kq9eJGMYktn/MpvAfpbqkSitoLCnFlZtuAve6eLh7NJxjZezuIhqkExiyK7O9xYcpGevNy1yjgkp+NG/sYzFuU1KS6NOeBhIPJe84iI1b7oVH/uOg7ZsvH3L5UuqkkLziX4kbkxQRNfitauJ/6A9zB/yBvFRE1oZqZUTSVZqZDASckgjWo43CyCmkWEv47CTMyTPyEnOOYVqpdrM9rKgB49EEOQuY1KlFoTpsI1H7MzATbGFIo8WvcEE/V0vEB3MQBuQit7B1M+wBSfzn2B8Auzypu5BQTs52NfD/fLUX/K4yYjo7P3ofHIjQNaY8p5gSDuUs/xlGzrVKD/Z3AR2IHg42nlkEuinEk9XfjNRqtuGpPBscdlteFJdFOP3P9ia/hw8aj90Qts0yndu/Vu0teMk9GwadO4kgjAdzr724yhOQDGeaRaKx5zqpvH/gZuMey2yOBgfqtFtCZsKaxgunt52Iq9yApw8QoMCuvSmzaMo+1wc2OizW6NdIKvPcqfkEsJc+OWR8XZvPa//YUjWXRSURJIvUUs2cdh07Hzs3m62z4oiNDP+2vlOn8eLNZbc3At4bXM+6as+hWKQ/QSmLKqbWR1k3K08Lr134xWo17TZitqlBGnwbt4IMvO8OaVlVeLth8aTlc2mhMa0JVJFp7e7z50FaOWTZ9+v/MumMyC/u3Md82NIm5+ff3wmLyhgXlEzs=
  template:
    metadata:
      name: argocd-notifications-secret
      namespace: argocd
