# Default values for frcdrn.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# We only consider cordoned nodes in a certain age range

# Testing values
# minAge: 0
# maxAge: 900
# schedule: "* * * * *"

# Production: We only consider nodes "stuck" for at least 10 minutes, at max 20.
# Worst case is that we detect it 14:59 after getting stuck
minAge: 600
maxAge: 1230
schedule: "*/5 * * * *"

# kind node defaults
labels: "!node-role.kubernetes.io/control-plane,!frcdrn/ignore"
# node-role.kubernetes.io/worker (openshift)

prometheusRule:
  create: true

image:
  repository: bitnami/kubectl
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations:
  - # key: "node-role.kubernetes.io/master"
    key: "node-role.kubernetes.io/control-plane" # kind
    operator: "Exists"
    effect: "NoSchedule"

affinity: {}
