apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: custom-tls
  namespace: openshift-config
spec:
  secretName: custom-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  issuerRef:
    name: cluster
    kind: ClusterIssuer
  commonName: my-app
  dnsNames:
    - my-app.example.com
