apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: foobar
  namespace: argocd
  # Add this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  #  env: local
  #  rev: main
  # Add labels to your application object.
  #labels:
  #  name: root
spec:
  project: default
  source:
    repoURL: https://github.com/deas/argocd-conductr.git
    targetRevision: main
    path: envs/foobar
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      # https://www.arthurkoziel.com/fixing-argocd-crd-too-long-error/
      - ServerSideApply=true
