apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  #- github.com/open-policy-agent/gatekeeper-library/library
  # You can optionally install a subset by specifying a subfolder, or specify a commit SHA
  - ../../base
  - github.com/open-policy-agent/gatekeeper-library/library/general/disallowedrepos/?ref=da229ba0e2807341b41b7e6c5eec3c2141b25e59
  - ./general/disallowedrepos/repo-must-not-be-k8s-gcr-io/constraint.yaml
#- constraint-repo-must-not-be-k8s-gcr-io.yaml
#- constraints.yaml
#transformers:
# TODO: kustomize order problem
#  - add-sync-wave-annotation.yaml
