controller:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
notifications:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
applicationSet:
  metrics:
    enabled: true
    metrics:
      serviceMonitor:
        enabled: true
repoServer:
  metrics:
    enabled: true
    metrics:
      serviceMonitor:
        enabled: true
server:
  metrics:
    enabled: true
    metrics:
      serviceMonitor:
        enabled: true
redis:
  metrics:
    enabled: true
    metrics:
      serviceMonitor:
        enabled: true
dex:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
