apiVersion: v1
kind: ConfigMap
metadata:
  name: cmp-kustomized-helm
  namespace: argocd
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: cmp-kustomized-helm
    spec:
      version: v1.0
      init:
        command: ["/bin/sh", "-c"]
        args: ["helm dependency build || true"]
      generate:
        command: ["/bin/sh", "-c"]
        args: ["helm template ../../helm_base --name-template $ARGOCD_APP_NAME --include-crds > ../../helm_base/all.yml && kustomize build"]
      #discover:
      #  find:
      #    command: [sh, -c, 'echo "FOUND"; exit 0']
      #allowConcurrency: true
      #lockRepo: true
