apiVersion: v1
kind: ConfigMap
metadata:
  name: cmp-cluster-env
  namespace: argocd
data:
  # TODO: Hacky path ../.. - doing this to leverage kustomize based ApplicationSet
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: cmp-cluster-env
    spec:
      version: v1.0
      generate:
        command: [sh, -c , 'cat ../../values-cluster-env.yaml | envsubst | helm -n argocd template -f - ../..' ]
      discover:
        fileName: "../../values-cluster-env.yaml"
        #find:
        ## This does the same thing as fileName, but it supports double-start (nested directory) glob patterns.
        #  glob: "**/values-cluster-env.yaml"
        #  # produce non-empty output to standard out.
        #  command: [sh, -c, 'echo "FOUND"; exit 0']
      allowConcurrency: true
      lockRepo: true
