# https://docs.okd.io/4.13/authentication/identity_providers/configuring-htpasswd-identity-provider.html#creating-htpasswd-file
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: htpasswd_provider 
    mappingMethod: claim 
    type: HTPasswd
    htpasswd:
      fileData:
        name: htpass