namespace: argocd
#resources:
# - ...
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
# Must be first if we want to pull it in from terraform
- name: argo-cd
  repo: https://argoproj.github.io/argo-helm
  version: "5.36.1"
  releaseName: argocd
  namespace: argocd
  valuesFile: values-argo-cd.yaml
  # valuesInline:
  #   fullnameOverride: helloagain
- name: argocd-image-updater
  repo: https://argoproj.github.io/argo-helm
  version: "0.9.1"
  releaseName: argocd-image-updater
  namespace: argocd
- name: argo-rollouts
  repo: https://argoproj.github.io/argo-helm
  version: "2.31.0"
  releaseName: argo-rollouts
  namespace: argocd
  valuesInline:
    controller:
      replicas: 1
# TODO: Not quite sure about the fate of the following - so we are dropping them into argocd ns      
- name: argo-events
  repo: https://argoproj.github.io/argo-helm
  version: "2.3.3"
  releaseName: argo-events
  namespace: argocd
# argocd notification is deprecated
