{{- if false }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: caretta
  namespace: argocd # default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  project: default
  source:
    repoURL: https://helm.groundcover.com/
    chart: caretta
    targetRevision: "0.0.16"
    helm:
      # Helm values files for overriding values in the helm chart
      # The path is relative to the spec.source.path directory defined above
      # valueFiles:
      # ../values-kube-prometheus.yaml' resolved to outside repository root
      #  - ../values-kube-prometheus.yaml
      #  - ../values-override.yaml
      values: |
        # TODO: We should move the grafana/prometheus bits over to kube-prometheus
        # TODO: Appears helm Capabilities are not respected for the PSPs?
        victoria-metrics-single:
          # enabled: false
          rbac:
            pspEnabled: false
        # grafana:
        #   enabled: false
        rbac:
          pspEnabled: false
        resources:
          limits:
            cpu: 150m
            memory: 600Mi # Default of 300Mi gets OOMKilled
  syncPolicy:
    syncOptions: # https://www.arthurkoziel.com/fixing-argocd-crd-too-long-error/
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
{{- end }}
