{{- if .Values.sealedSecrets.enabled }}
# helm install sealed-secrets -n kube-system --set-string fullnameOverride=sealed-secrets-controller sealed-secrets/sealed-secrets
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd # default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  project: default
  source:
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    chart: sealed-secrets
    targetRevision: "2.16.1"
    helm:
      # Helm values files for overriding values in the helm chart
      # The path is relative to the spec.source.path directory defined above
      # valueFiles:
      # ../values-kube-prometheus.yaml' resolved to outside repository root
      #  - ../values-kube-prometheus.yaml
      #  - ../values-override.yaml
      # values: |
      valuesObject:
        fullnameOverride: sealed-secrets-controller
        #
  syncPolicy:
    syncOptions: []
    automated:
      prune: true
      selfHeal: true
{{- end }}
