apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: kargo-default-repo
  namespace: kargo-default
  labels:
    kargo.akuity.io/cred-type: git
stringData:
  repoURL: https://github.com/deas/argocd-conductr.git
  username: ${GITHUB_USERNAME}
  password: ${GITHUB_PAT}
