{{ if .Capabilities.APIVersions.Has "monitoring.coreos.com/v1alpha/AlertmanagerConfig" -}}
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: "{{ include "monitoring-webhook.fullname" . }}"
  namespace: "{{ .Release.Namespace }}" 
  labels:
    alertmanagerConfig: prometheus
spec:
  route:
    receiver: "webhook-receiver"
    #matchers: []
  receivers:
    - name: "webhook-receiver"
      webhookConfigs:
        - url: "http://{{ include "monitoring-webhook.fullname" . }}:{{ .Values.service.port }}/alerts"
          #httpConfig:
          #  enable_http2: false # Not supported by CRD
{{- end}}
