{{- if and (.Values.serviceAccount.create) (.Values.serviceAccount.existingClusterRole) -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "monitoring-webhook.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.serviceAccount.existingClusterRole }}
subjects:
  - kind: ServiceAccount
    name: {{ include "monitoring-webhook.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end}}
