apiVersion: audit.k8s.io/v1
kind: Policy
rules:
  - level: Metadata
    resources:
      - group: operators.coreos.com
        resources: ["subscriptions"]
    verbs: ["create", "update", "delete", "patch", "get", "list", "watch"]
