apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: local-ops
    argocd.argoproj.io/sync-options: Prune=false
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/infra/argo-cd/envs/local
    repoURL: https://github.com/deas/argocd-conductr.git
    targetRevision: wip
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      # https://www.arthurkoziel.com/fixing-argocd-crd-too-long-error/
      - ServerSideApply=true
      - CreateNamespace=true
