apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: foobar-ops
    argocd.argoproj.io/sync-options: Prune=false
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  sources:
    - chart: argo-cd
      helm:
        valueFiles:
                  - $values/apps/infra/argo-cd/envs/foobar-helm/../../values.yaml
                  - $values/apps/infra/argo-cd/envs/foobar-helm/values.yaml
      repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 7.6.8
    - ref: values
      repoURL: https://github.com/deas/argocd-conductr.git
      targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      # https://www.arthurkoziel.com/fixing-argocd-crd-too-long-error/
      - ServerSideApply=true
      - CreateNamespace=true
