apiVersion: v1
data:
  {{- (.Files.Glob "assets/argo**.json").AsConfig | nindent 2 }}
kind: ConfigMap
metadata:
  name: misc-dashboards
    #labels:
    #  - include "monitoring.labels" . | nindent 4 
  namespace: "{{ .Release.Namespace }}"
  labels:
    grafana_dashboard: "1"
