apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          # - cluster: {}
          - list:
              elements:
                - appName: ingress-nginx
                  repoURL: https://kubernetes.github.io/ingress-nginx
                  namespace: ingress
                  targetRevision: "4.7.1"
                - appName: loki
                  repoURL: https://grafana.github.io/helm-charts
                  namespace: monitoring
                  targetRevision: "4.8.0" # "5.0.0" is out
                - appName: kube-prometheus-stack
                  repoURL: https://prometheus-community.github.io/helm-charts
                  namespace: monitoring
                  targetRevision: "45.7.1" # "65.1.0"
                - appName: sealed-secrets
                  repoURL: https://bitnami-labs.github.io/sealed-secrets
                  namespace: kube-system
                  targetRevision: "2.16.1"
              # chart: sealed-secrets
          - git:
              repoURL: https://github.com/deas/argocd-conductr.git
              revision: wip # HEAD
              directories:
                - path: "apps/infra/{{ .appName }}/envs/local"
              # apps/*envs/local
              # - path: apps/*/envs/local
  template:
    metadata:
      # We don't env/stage at the name level
      name: "{{index .path.segments 2}}" # -{{index .path.segments 3}}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      # The project the application belongs to.
      project: default

      # Source of the application manifests
      sources:
        # repoURL: https://github.com/deas/argocd-conductr.git
        # targetRevision: wip
        # path: "{{.path.path}}"
        - repoURL: "{{ .repoURL }}"
          chart: "{{ .appName }}"
          targetRevision: "{{ .targetRevision }}"
          helm:
            # Helm values files for overriding values in the helm chart
            # The path is relative to the spec.source.path directory defined above
            valueFiles:
              - "$values/{{ .path.path }}/../../values.yaml"
              - "$values/{{ .path.path }}/values.yaml"
        - repoURL: https://github.com/deas/argocd-conductr.git
          targetRevision: wip
          ref: values
      # Destination cluster and namespace to deploy the application
      destination:
        server: https://kubernetes.default.svc
        # We don't stage/env at the ns level
        # namespace: "{{index .path.segments 2}}" # -{{index .path.segments 3}}'
        namespace: "{{ .namespace }}"

      # Sync policy
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
          prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
          selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).

