name: test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: ["*"]
    tags-ignore: ["*"]

jobs:
  manifests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup tools
        uses: ./.github/actions/tools
      - uses: jdx/mise-action@v2
        with:
          version: 2024.10.0 # [default: latest] mise version to install
          install: true # [default: true] run `mise install`
          # install_args: "bun" # [default: ""] additional arguments to `mise install`
          # cache: true # [default: true] cache mise using GitHub's cache
          # automatically write this .tool-versions file
          experimental: true # [default: false] enable experimental features
          log_level: debug # [default: info] log level
          #tool_versions: |
          #  shellcheck 0.9.0
          # or, if you prefer .mise.toml format:
          #mise_toml: |
          #  [tools]
          #  gator = "3.17.1"
          # working_directory: app # [default: .] directory to run mise in
      - name: Validate manifests
        run: ./tools/validate.sh
