apiVersion: v1
data:
{{ $root := . }}
{{ range $path, $bytes := .Files.Glob "assets/*"}}
  {{ base $path }}: |
{{ $root.Files.Get $path | indent 4 }}
{{ end }}
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-templates"
  namespace: "{{ .Release.Namespace }}"
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "submariner.chart" . }}
    app: {{ template "submariner.name" . }}
