apiVersion: v1
kind: ServiceAccount
metadata:
  name: broker-reader
  namespace: submariner-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: endpoint-reader
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: broker-secret-reader
  namespace: submariner-k8s-broker
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-endpoints
  namespace: default
subjects:
  - kind: ServiceAccount
    name: broker-reader
    namespace: submariner-operator
roleRef:
  kind: Role
  name: endpoint-reader
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-secrets
  namespace: submariner-k8s-broker
subjects:
  - kind: ServiceAccount
    name: broker-reader
    namespace: submariner-operator
roleRef:
  kind: Role
  name: broker-secret-reader
  apiGroup: rbac.authorization.k8s.io
